/**
 * scripts/lib/wp-css-injector.ts
 * UMBAUPLAN v2.0 Phase 3.1 — Workaround for Elementor 4.1.0-beta1 0-byte CSS bug.
 */

import { createHash } from 'node:crypto';

export interface McpBridgeLike {
  call(ability: string, params: Record<string, unknown>): Promise<Record<string, unknown>>;
}

export interface InjectResult {
  success: boolean;
  css_url?: string;
  mu_plugin_path?: string;
  css_hash?: string;
  error?: string;
}

export interface RemoveResult {
  success: boolean;
}

export interface WpCssInjector {
  siteId: string;
  injectCustomCss: (opts: { post_id: number; css: string }) => Promise<InjectResult>;
  removeCustomCss: (opts: { post_id: number }) => Promise<RemoveResult>;
}

export interface V4Tree {
  styles?: Record<string, V4StyleClass>;
  elements?: V4Tree[];
  children?: V4Tree[];
  [key: string]: unknown;
}

export interface V4StyleClass {
  variants?: V4Variant[];
}

export interface V4Variant {
  meta?: { breakpoint?: string | null; state?: string | null };
  props?: Record<string, V4Value>;
}

export interface V4Value {
  '$$type'?: string;
  value?: { size?: number; unit?: string } | unknown;
  [key: string]: unknown;
}

export function generateCssFromV4Tree(tree: V4Tree | null): string {
  if (!tree || typeof tree !== 'object') return '';
  const blocks: string[] = [];
  walkForCss(tree, blocks);
  return blocks.join('\n\n');
}

function walkForCss(node: V4Tree, blocks: string[]): void {
  if (!node || typeof node !== 'object') return;
  if (node.styles && typeof node.styles === 'object') {
    for (const [styleId, styleDef] of Object.entries(node.styles)) {
      const variants = styleDef.variants || [];
      for (const variant of variants) {
        const css = renderVariant(styleId, variant);
        if (css.trim()) blocks.push(css);
      }
    }
  }
  const children = node.elements || node.children || [];
  for (const child of children) walkForCss(child, blocks);
}

function renderVariant(classId: string, variant: V4Variant): string {
  if (!variant || !variant.props) return '';
  const lines: string[] = [];
  for (const [prop, value] of Object.entries(variant.props)) {
    const cssVal = unwrapV4Value(value);
    if (cssVal) lines.push(`  ${prop}: ${cssVal};`);
  }
  if (lines.length === 0) return '';
  const selector = `.${classId}`;
  const state = variant.meta?.state;
  const breakpoint = variant.meta?.breakpoint;
  let block = `${selector}${state ? ':' + state : ''} {\n${lines.join('\n')}\n}`;
  if (breakpoint && breakpoint !== 'desktop') {
    const bpQuery = breakpointToMedia(breakpoint);
    if (bpQuery) block = `@media ${bpQuery} {\n${block}\n}`;
  }
  return block;
}

function unwrapV4Value(value: V4Value | string): string {
  if (!value || typeof value !== 'object') return '';
  if (typeof value === 'string') return value;
  if (value['$$type'] === 'size') return `${(value.value as Record<string, number | string>)?.size ?? 0}${(value.value as Record<string, string>)?.unit ?? 'px'}`;
  if (value['$$type'] === 'string') return (value.value as string) ?? '';
  if (value['$$type'] === 'color') return (value.value as string) ?? '';
  if (value['$$type'] === 'dimensions') {
    const v = (value.value || {}) as Record<string, V4Value>;
    const get = (key: string) => unwrapV4Value(v[key]);
    return `${get('block-start')} ${get('inline-end')} ${get('block-end')} ${get('inline-start')}`;
  }
  if (value['$$type'] === 'border-radius') {
    const v = (value.value || {}) as Record<string, V4Value>;
    return `${unwrapV4Value(v['start-start'])} ${unwrapV4Value(v['start-end'])} ${unwrapV4Value(v['end-end'])} ${unwrapV4Value(v['end-start'])}`;
  }
  return '';
}

function breakpointToMedia(breakpoint: string): string | null {
  switch (breakpoint) {
    case 'tablet':  return '(max-width: 1024px)';
    case 'mobile':  return '(max-width: 767px)';
    case 'widescreen': return '(min-width: 1440px)';
    case 'laptop':  return '(max-width: 1366px)';
    default: return null;
  }
}

export function generateMuPluginContent(postId: number, cssFileUrl: string): string {
  return `<?php
/**
 * Auto-generated by novamira-adrianv2 / framer-v4-pipeline (UMBAUPLAN Phase 3.1).
 * Enqueues custom CSS for post_id=${postId} only.
 * DO NOT EDIT — will be overwritten on next build.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'wp_enqueue_scripts', function () {
  if ( is_singular( ${postId} ) ) {
    wp_enqueue_style(
      'novamira-custom-css-${postId}',
      '${cssFileUrl.replace(/'/g, "\\'")}',
      array(),
      filemtime( WP_CONTENT_DIR . '/uploads/elementor-custom-css/post-${postId}.css' ) ?: '1.0'
    );
  }
} );
`;
}

export function createWpCssInjector({ mcpBridge, siteId }: {
  mcpBridge: McpBridgeLike;
  siteId: string;
}): WpCssInjector {
  if (!mcpBridge) throw new Error('createWpCssInjector: mcpBridge required');
  if (!siteId) throw new Error('createWpCssInjector: siteId required');

  async function injectCustomCss({ post_id, css }: { post_id: number; css: string }): Promise<InjectResult> {
    if (!post_id || typeof post_id !== 'number') {
      throw new Error('injectCustomCss: post_id (number) required');
    }
    if (typeof css !== 'string') {
      throw new Error('injectCustomCss: css (string) required');
    }

    const cssFilename = `post-${post_id}.css`;
    const cssUrl = `/wp-content/uploads/elementor-custom-css/${cssFilename}`;
    const cssHash = createHash('md5').update(css).digest('hex').slice(0, 8);
    const muPluginPath = `wp-content/mu-plugins/elementor-custom-css-${post_id}.php`;

    const uploadResult = await mcpBridge.call('create-upload-link', {
      filename: cssFilename,
      content: css,
    }).catch((err: Error) => ({ error: err.message }));

    if ((uploadResult as Record<string, unknown>).error) {
      return { success: false, error: `css-upload: ${(uploadResult as Record<string, string>).error}` };
    }

    const muPluginCode = generateMuPluginContent(post_id, cssUrl);
    const muResult = await mcpBridge.call('execute-php', {
      code: muPluginCode,
      path: muPluginPath,
    }).catch((err: Error) => ({ error: err.message }));

    if ((muResult as Record<string, unknown>).error) {
      return { success: false, error: `mu-plugin: ${(muResult as Record<string, string>).error}`, css_url: cssUrl };
    }

    return { success: true, css_url: cssUrl, mu_plugin_path: muPluginPath, css_hash: cssHash };
  }

  async function removeCustomCss({ post_id }: { post_id: number }): Promise<RemoveResult> {
    const muPluginPath = `wp-content/mu-plugins/elementor-custom-css-${post_id}.php`;
    const cssFilePath = `wp-content/uploads/elementor-custom-css/post-${post_id}.css`;

    await mcpBridge.call('execute-php', {
      code: '<?php if (file_exists($path)) unlink($path);',
      path: muPluginPath,
      unlink: true,
    }).catch(() => null);

    await mcpBridge.call('execute-php', {
      code: '<?php if (file_exists($path)) unlink($path);',
      path: cssFilePath,
      unlink: true,
    }).catch(() => null);

    return { success: true };
  }

  return { siteId, injectCustomCss, removeCustomCss };
}
